# Generated by Django 5.1.3 on 2024-11-15 13:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='rating',
        ),
        migrations.AddField(
            model_name='hotel',
            name='description',
            field=models.CharField(default='Пока здесь пусто', max_length=200),
        ),
        migrations.AddField(
            model_name='hotel',
            name='owner_name',
            field=models.CharField(default='Не установлен', max_length=80),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('price_per_night', models.IntegerField()),
                ('room_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('twin', 'Twin'), ('triple', 'Triple'), ('quadriple', 'Quadriple')], max_length=50)),
                ('quality', models.CharField(choices=[('standard', 'Standard'), ('superior', 'Superior'), ('lux', 'Lux')], max_length=50)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelservice.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelservice.room')),
                ('user_nick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelservice.user')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelservice.room')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelservice.user')),
            ],
        ),
    ]
