# Generated by Django 5.1.3 on 2025-02-24 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0003_show_sponsor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='ring',
        ),
        migrations.AlterField(
            model_name='dogtoshow',
            name='dog',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='show.dog'),
        ),
        migrations.AlterField(
            model_name='dogtoshow',
            name='ring',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.ring'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='ring',
            field=models.ManyToManyField(to='show.ring'),
        ),
    ]
