# Generated by Django 5.1.7 on 2025-03-14 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("show", "0004_remove_curriculum_ring_alter_dogtoshow_dog_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="show",
            name="sponsor",
        ),
    ]
