# Generated by Django 5.1.7 on 2025-03-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("show", "0005_remove_show_sponsor"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="sponsor",
            field=models.ManyToManyField(to="show.sponsor"),
        ),
    ]
