# Generated by Django 5.1.7 on 2025-03-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("show", "0006_show_sponsor"),
    ]

    operations = [
        migrations.AddField(
            model_name="curriculum",
            name="end_time",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="curriculum",
            name="start_time",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="dog",
            name="age",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dogtoshow",
            name="payment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="exercise",
            name="first",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="exercise",
            name="second",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="exercise",
            name="third",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="medicalexamination",
            name="date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="medicalexamination",
            name="result",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="place",
            name="capacity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ring",
            name="number",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="show",
            name="date",
            field=models.DateTimeField(null=True),
        ),
    ]
