# Generated by Django 5.1.7 on 2025-03-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("show", "0007_curriculum_end_time_curriculum_start_time_dog_age_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="passport",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="user",
            name="patronymic",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
