# Generated by Django 5.1.7 on 2025-03-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("show", "0008_alter_user_passport_alter_user_patronymic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="email address"),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=150, verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=150, verbose_name="last name"),
        ),
    ]
